### PR TITLE
update to 1.19.3

### PR DESCRIPTION
**Pull request by moehreag**
- [ ] Fix crash on startup: FileNotFound exception stating the shader files cannot be found. No idea how to fix this.

### CODE REVIEW

**Comment by rayzchen** [comment]
When will this be ready?

**Comment by moehreag** [comment]
when Dark ports the shader handling to use the Satin library

**Comment by rayzchen** [comment]
so is this fixed?

**Comment by DarkKronicle** [comment]
Yeah, it should be published today, but if you go to actions there is a build. Same with KronHUD

**Pull request closed without merging**
